version: '2.15.1'

networks:
  default:
    external: true
    name: medianet
    driver: bridge

services:
  jellyfin: # open source media server
    image: linuxserver/jellyfin:10.8.9-1-ls199
    container_name: jellyfin
    networks:
      - default
    ports: 
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 1900:1900/udp
      - 7359:7359/udp
    environment:
      - PUID = 1000
      - PGID = 1000
      - TZ = America/Costa_Rica
    volumes:
      - M:\jellyfin\config:/config
      - M:\jellyfin\cache:/cache
      - M:\movies:/data/movies:rw # rw permissions to install plugins
      - M:\tv:/data/tv:rw
      - M:\music:/data/music:rw
      - M:\videos:/data/videos:rw
      - M:\books:/data/books:rw
    restart: 'unless-stopped'
  radarr: # movie collection manager
    image: linuxserver/radarr:4.3.2.6857-ls160
    container_name: radarr
    networks:
      - default
    ports:
      - 7878:7878/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Costa_Rica
    volumes:
      - M:\radarr\config:/config
      - M:\movies:/movies
      - M:\downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
  sonarr: # tv shows collection manager
    image: linuxserver/sonarr:3.0.9.1549-ls176
    container_name: sonarr
    networks:
      - default
    ports:
      - 8989:8989/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Costa_Rica
    volumes:
      - M:\sonarr\config:/config
      - M:\tv:/tv #optional
      - M:\downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
  lidarr: # music collection manager
    image: linuxserver/lidarr:1.0.2.2592-ls110
    container_name: lidarr
    networks:
      - default
    ports:
      - 8686:8686/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Costa_Rica
    volumes:
      - M:\lidarr\config:/config
      - M:\music:/music #optional
      - M:\downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
  readarr: # books collection manager
    image: linuxserver/readarr:develop
    container_name: readarr
    networks:
      - default
    ports:
      - 8787:8787/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Costa_Rica
    volumes:
      - M:\readarr\config:/config
      - M:\books:/books #optional
      - M:\downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
  jackett: # proxy server
    image: linuxserver/jackett:v0.20.3063-ls92
    container_name: jackett
    networks:
      - default
    ports:
      - 9117:9117/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Costa_Rica
      - AUTO_UPDATE=true #optional
    volumes:
      - M:\jackett\config:/config
      - M:\downloads:/downloads
    restart: unless-stopped
  qbittorrent: # torrent manager
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - default
    ports:
      - 8080:8080/tcp
      - 8010:8010
      # - 6881:6881/tcp
      # - 6881:6881/udp
      - 63407:63407/tcp # custom ports may be faster
      - 63407:63407/udp # custom ports may be faster
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - INCOMING_WEB_PORT=6881
      - FILE__VPN_USERNAME =  ${VPN_USERNAME}
      - FILE__VPN_PASSWORD =  ${VPN_PASSWORD}
      - NAME_SERVERS=8.8.8.8, 8.8.4.4
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.100.35
      - TZ = America/Costa_Rica
    volumes:
      - M:\qbittorrent\config:/config
      - M:\downloads:/downloads
    restart: unless-stopped
# ====================================== OPTIONAL SERVICES =======================================
  # plex: # alternate media server
  #   image: plexinc/pms-docker
  #   container_name: plex
  #   restart: unless-stopped
  #   hostname: BajuraFlix
  #   environment:
  #     - TZ = America/Costa_Rica
  #     - PLEX_CLAIM=claim-GEnWZU-PiYXga7djaHUr
  #     #- ADVERTISE_IP = http://localhost:32400/
  #   ports:
  #     - 32400:32400/tcp
  #     - 3005:3005/tcp
  #     - 8324:8324/tcp
  #     - 32469:32469/tcp
  #     - 1900:1900/udp
  #     - 32410:32410/udp
  #     - 32412:32412/udp
  #     - 32413:32413/udp
  #     - 32414:32414/udp
  #   volumes:
  #     - M:\plex\config:/config
  #     - M:\plex\transcode:/transcode
  #     - M:\movies:/movies:ro
  # pktriot: # reverse proxy
  #   image: packetriot/pktriot:latest
  #   container_name: pktriot
  #   restart: unless-stopped
  #   volumes:
  #       - M:\plex\pktriot:/data
  #       - M:\plex\www:/www:ro
  # qbittorrentvpn: # qbittorrent alternative image
  #   image: markusmcnugen/qbittorrentvpn:latest
  #   container_name: qbittorrentvpn
  #   privileged: true
  #   environment:
  #     - VPN_USERNAME =  ${VPN_USERNAME}
  #     - VPN_PASSWORD =  ${VPN_PASSWORD}
  #     - PUID=1000
  #     - PGID=1000
  #     - WEBUI_PORT=8080
  #     - INCOMING_WEB_PORT=8999
  #     - VPN_ENABLED=yes
  #     - NAME_SERVERS=8.8.8.8, 8.8.4.4
  #     - LAN_NETWORK=192.168.100.35/24
  #     - TZ = America/Costa_Rica
  #     # - UMASK=002
  #   volumes:
  #     - M:\qbittorrentvpn\config:/config
  #     - M:\downloads:/downloads
  #   ports:
  #     - 8080:8080/tcp
  #     - 8999:8999/tcp
  #     - 8999:8999/udp
  #   restart: unless-stopped
# ======================================  / OPTIONAL SERVICES =======================================